#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

  ${symbol_pound}${symbol_pound} Configuración Server
server:
  port: 8080
  servlet:
    context-path: /${artifactId}

  ${symbol_pound}${symbol_pound} Configuración Spring
spring:
  application:
    name: ${artifactId}
    description: Estructura base  proyecto PICAP ${ArtifactIdCamel}
    version: ${version}
  datasource:
    password: ${symbol_dollar}{dbpassword:123456789Interventoria}
    url: ${symbol_dollar}{dbconexion:jdbc:postgresql://db.aaushzsjiqmjoqaoxjmk.supabase.co:5432/Interventoria}
    username: ${symbol_dollar}{dbusername:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jackson:
    time-zone: America/Bogota
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true